Repository hostolab/covidliste, pull requests merged in 2021-05, with the labels that each got.

#708 Update email footer
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/magic_link.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/mailer/_automatic_message.html.erb
  app/views/mailer/_footer.html.erb
  app/views/match_mailer/match_confirmation_instructions.html.erb
  app/views/match_mailer/send_anonymisation_notice.html.erb
  config/locales/devise.fr.yml
Labels: ready for review

#681 Improve new campaign slack notification
  app/jobs/push_new_campaign_to_slack_job.rb
  app/jobs/slack_notifier_job.rb
Labels: ready for review

#695 Automatisation de l'email de confirmation d'un centre de vaccination
  app/controllers/admin/vaccination_centers_controller.rb
  app/jobs/send_vaccination_center_confirmation_email_job.rb
  app/mailers/match_mailer.rb
  app/mailers/vaccination_center_mailer.rb
  app/views/vaccination_center_mailer/confirmed_vaccination_center_onboarding.html.erb
  db/migrate/20210503104709_add_confirmation_mail_sent_at_to_vaccination_centers.rb
  db/schema.rb
  spec/jobs/send_vaccination_center_confirmation_email_job.spec.rb
Labels: ready for review

#715 Avertissement avant de lancer une campagne si des campagnes sont déjà en cours
  app/javascript/components/partners/campaign_creator/CampaignCreator.jsx
  app/javascript/components/partners/campaign_creator/CampaignCreatorAlreadyRunningCampaignWarning.jsx
Labels: ready for review

#726 Ajout d'un indicateur email envoyé/non envoyé dans l'interface admin/centres de vaccination
  app/views/admin/vaccination_centers/show.html.erb
Labels: ready for review

#730 Update du mail d'anonymisation
  app/mailers/match_mailer.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/magic_link.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/mailer/_faq.html.erb
  app/views/mailer/_footer.html.erb
  app/views/match_mailer/match_confirmation_instructions.html.erb
  app/views/match_mailer/send_anonymisation_notice.html.erb
  app/views/vaccination_center_mailer/confirmed_vaccination_center_onboarding.html.erb
Labels: ready for review

#742 Update du flow de confirmation de match pour desktop et mobile
  app/javascript/components/toggle_mobile_match_information.js
  app/javascript/packs/application.js
  app/views/match_mailer/match_confirmation_instructions.html.erb
  app/views/matches/_confirmed.html.erb
  app/views/matches/_expired.html.erb
  app/views/matches/_identity_form.html.erb
  app/views/matches/_match_details.html.erb
  app/views/matches/_overbooked.html.erb
  app/views/matches/_pending.html.erb
  app/views/matches/_refused.html.erb
  app/views/matches/show.html.erb
  config/locales/devise.fr.yml
  spec/system/matches_controller_spec.rb
Labels: ready for review

#770 Fix browser form validation display on Chrome
  app/javascript/components/confirmation.js
Labels: ready for review

#783 Envoi d'un email à l'utilisateur suite à la confirmation du match
  app/controllers/matches_controller.rb
  app/jobs/send_confirmed_match_email_job.rb
  app/mailers/match_mailer.rb
  app/views/match_mailer/send_confirmed_match_details.html.erb
  app/views/matches/_confirmed.html.erb
  app/views/matches/_match_details.html.erb
  db/migrate/20210515232244_add_confirmed_mail_sent_at_to_matches.rb
  db/schema.rb
  spec/jobs/send_confirmed_match_mail_job.spec.rb
  test/mailers/previews/match_mailer_preview.rb
Labels: ready for review

#782 Changement du nom du champ extra info "Infos supplémentaires" > "Détails d'accès"
  app/javascript/components/partners/campaign_creator/CampaignCreator.jsx
  app/javascript/components/partners/campaign_creator/fields/CampaignCreatorExtraInfo.jsx
  app/views/partners/new.html.erb
Labels: ready for review

#805 Re-ajout du nom prénom dans Match details
  app/views/matches/_match_details.html.erb
Labels: P1, ready for review

#804 Empêcher les matchs confirmés de supprimer leur compte
  app/controllers/matches/users_controller.rb
  app/views/matches/users/edit.html.erb
  spec/system/matches/destroy_user_account_spec.rb
Labels: P1

#786 Fix access rights for support_member volunteers
  app/policies/admin/campaign_policy.rb
  app/policies/admin/home_policy.rb
  app/policies/admin/stats_policy.rb
  app/policies/admin/user_policy.rb
  app/policies/admin/vaccination_center_policy.rb
  app/views/layouts/_admin_navbar.html.erb
  config/routes.rb
Labels: ready for review

#803 Mise à jour des textes des mails aux particuliers
  app/mailers/devise_mailer.rb
  app/mailers/match_mailer.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/magic_link.html.erb
  app/views/layouts/mailer.html.erb
  app/views/mailer/_faq.html.erb
  app/views/mailer/_footer.html.erb
  app/views/match_mailer/match_confirmation_instructions.html.erb
  app/views/match_mailer/send_anonymisation_notice.html.erb
  app/views/match_mailer/send_confirmed_match_details.html.erb
  config/locales/devise.fr.yml
  test/mailers/previews/devise_mailer_preview.rb
Labels: ready for review

#849 Remove marker grouping from map
  app/assets/stylesheets/components/_spinner.scss
  app/assets/stylesheets/components/campaign_creator/_CampaignCreatorReach.scss
  app/controllers/pages_controller.rb
  app/controllers/vaccination_centers_controller.rb
  app/javascript/components/partners/campaign_creator/CampaignCreatorReach.jsx
  app/javascript/plugins/leaflet_map.js
  app/models/vaccination_center.rb
  app/views/admin/stats/stats.html.erb
  app/views/admin/vaccination_centers/show.html.erb
  app/views/pages/carte.erb
  app/views/partners/vaccination_centers/show.html.erb
  config/routes.rb
  package.json
  yarn.lock
Labels: ready for review

#890 Update wording Landing pro
  app/views/pages/landing_page_pro.html.erb
Labels: ready for review

#864 Forward user to other match if available
  app/controllers/matches_controller.rb
  app/models/match.rb
  app/views/partners/vaccination_centers/show.html.erb
  spec/factories/match_multi_factory.rb
  spec/models/match_spec.rb
  test/mailers/previews/match_mailer_preview.rb
Labels: ready for review
