Repository hostolab/covidliste, pull requests merged in 2021-04, with the labels that each got.

#379 Prompt user to check Age & Name when matched
  .gitignore
  app/controllers/matches_controller.rb
  app/views/layouts/_footer.html.erb
  app/views/matches/_match_details.html.erb
  app/views/matches/_pending.html.erb
  app/views/matches/show.html.erb
Labels: P0

#303 Dataviz v1
  .editorconfig
  app/assets/stylesheets/application.scss
  app/javascript/controllers/carte/departements-version-simplifiee.json
  app/javascript/controllers/carte/map_controller.js
  app/javascript/controllers/carte/pop2021.json
  app/views/layouts/_navbar.html.haml
  app/views/pages/carte.erb
  config/routes.rb
  package.json
  yarn.lock
Labels: P1

#393 Afficher les informations suppl sur Slack
  app/jobs/push_new_campaign_to_slack_job.rb
Labels: P1

#392 Ajout d'un age minimum pour vaccin J&J
  app/javascript/controllers/new_campaign_controller.js
Labels: P1, ready for review

#395 Expliquer que les extra infos ne sont visibles qu'après confirmation des volontaires
  app/views/partners/campaigns/new.html.haml
Labels: P1

#380 Add invisible capatcha to user and partner form inscription #370
  Gemfile
  Gemfile.lock
  app/controllers/partners_controller.rb
  app/controllers/users_controller.rb
  app/views/partners/new.html.erb
  app/views/users/_form.html.erb
  config/initializers/invisible_captcha.rb
Labels: ready for review

#388 Remove admin protection on /carte
  app/javascript/controllers/carte/map_controller.js
  app/views/layouts/_navbar.html.haml
  app/views/pages/carte.erb
Labels: ready for review

#368 Display a nicer confirmation modal
  app/javascript/components/confirmation.js
  app/javascript/packs/application.js
  spec/rails_helper.rb
  spec/support/helpers/system_spec_helpers.rb
  spec/system/admin/users_spec.rb
  spec/system/partner_spec.rb
  spec/system/user_spec.rb
Labels: ready for review

#400 Fix typo Guadeloupe
  app/javascript/controllers/carte/map_controller.js
Labels: ready for review

#407 Fix CSP headers for the map
  app/controllers/application_controller.rb
Labels: P0

#414 Fix conditions in partners/vaccination_centers#index
  app/views/partners/vaccination_centers/index.html.erb
Labels: P0

#421 Format the Algolia suggestion with the zip code and without the region
  app/javascript/plugins/places_autocomplete.js
Labels: P1

#403 Minor updates to README
  README.md
Labels: ready for review

#389 Split maps JS pack
  app/javascript/controllers/application/index.js
  app/javascript/controllers/application/new_campaign_controller.js
  app/javascript/controllers/maps/departements-version-simplifiee.json
  app/javascript/controllers/maps/index.js
  app/javascript/controllers/maps/map_controller.js
  app/javascript/controllers/maps/pop2021.json
  app/javascript/packs/application.js
  app/javascript/packs/maps.js
  app/views/pages/carte.erb
  spec/system/carte_spec.rb
Labels: ready for review

#373 fix: Make validation on lat lon contextual for VaccinationCenter
  app/controllers/admin/vaccination_centers_controller.rb
  app/models/vaccination_center.rb
  spec/models/vaccination_center_spec.rb
Labels: ready for review

#416 add support for Turbolinks to show hide password functionality
  app/javascript/components/toggle_password_visibility.js
  app/javascript/packs/application.js
Labels: ready for review

#429 Geocode centers with Data.gouv api
  app/controllers/partners/vaccination_centers_controller.rb
  app/javascript/plugins/places_autocomplete.js
  app/jobs/geocode_resource_job.rb
  app/jobs/geocode_user_job.rb
  app/models/user.rb
  app/models/vaccination_center.rb
  app/services/geocoding_service.rb
  app/views/partners/vaccination_centers/new.html.erb
  spec/factories/vaccination_center_factory.rb
  spec/jobs/geocode_resource_job_spec.rb
  spec/jobs/geocode_user_job_spec.rb
Labels: ready for review

#426 Empêche un user de modifier ces informations après un match confirmé
  app/controllers/users_controller.rb
  app/models/match.rb
  app/policies/user_policy.rb
  config/locales/fr.yml
  spec/system/user_spec.rb
Labels: ready for review

#442 chiffres sur la home page
  app/controllers/users_controller.rb
  app/views/users/_about.html.erb
Labels: ready for review

#417 Active Turbolinks
  app/views/layouts/admin_application.html.erb
  app/views/layouts/application.html.erb
Labels: ready for review

#466 Remove undefined from Algolia addresses
  app/javascript/plugins/places_autocomplete.js
Labels: P1, bug

#431 Better display of match dates
  app/jobs/anonymize_confirmed_matched_users_job.rb
  app/views/matches/_confirmed.html.erb
  app/views/matches/_match_details.html.erb
  app/views/matches/_pending.html.erb
  config/locales/fr.yml
  config/schedule.yml
Labels: ready for review

#486 Mise à jour du header + footer + logo
  app/assets/images/covidliste-logo.png
  app/assets/stylesheets/components/_background.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_links.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_index.scss
  app/assets/stylesheets/config/_navbar.scss
  app/views/layouts/_admin_navbar.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_navbar.html.erb
Labels: ready for review

#484 Validation pas de match récent
  app/models/match.rb
  spec/models/match_spec.rb
Labels: P1, ready for review

#483 Complexité mot de passe
  Gemfile
  Gemfile.lock
  app/javascript/controllers/application/password_controller.js
  app/models/partner.rb
  app/models/user.rb
  app/views/devise/passwords/edit.html.erb
  app/views/partners/new.html.erb
  app/views/users/_form.html.erb
  config/initializers/devise.rb
  config/locales/devise.fr.yml
  lib/tasks/populate.rake
  package.json
  spec/factories/sequence_factory.rb
  spec/models/match_spec.rb
  spec/models/user_spec.rb
  spec/system/user_spec.rb
  yarn.lock
Labels: P1

#501 Nouvelles pages CGU, cookies, privacy...
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_static_page.scss
  app/controllers/pages_controller.rb
  app/models/static_page.rb
  app/views/layouts/_footer.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/static.html.erb
  config/routes.rb
  db/frozen_records/static_pages.yml
  spec/system/cookies_spec.rb
  spec/system/mentions_legales_spec.rb
  spec/system/privacy_pages_spec.rb
  spec/system/privacy_spec.rb
  spec/system/terms_spec.rb
Labels: P1, ready for review

#505 Romain/474 legal updates
  app/controllers/partners_controller.rb
  app/controllers/users_controller.rb
  app/models/partner.rb
  app/views/layouts/_footer.html.erb
  app/views/pages/benevoles.html.erb
  app/views/partners/new.html.erb
  app/views/users/_form.html.erb
  app/views/users/_input_statement.html.erb
  app/views/users/_input_toc.html.erb
  app/views/users/_mentions.html.erb
  app/views/users/show.html.erb
  db/frozen_records/static_pages.yml
  db/migrate/20210419221713_add_statement_to_partners.rb
  db/migrate/20210419230519_add_statement_and_toc_accepted_at_to_users.rb
  db/migrate/20210419230614_add_statement_accepted_at_to_partners.rb
  db/schema.rb
  spec/factories/partner_factory.rb
  spec/system/partner_spec.rb
  spec/system/user_spec.rb
Labels: P1, ready for review

#419 feat(authz): Migrate admin namespace to pundit
  app/controllers/admin/base_controller.rb
  app/controllers/admin/home_controller.rb
  app/controllers/admin/power_users_controller.rb
  app/controllers/admin/stats_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/admin/vaccination_centers_controller.rb
  app/policies/admin/home_policy.rb
  app/policies/admin/power_users/user_policy.rb
  app/policies/admin/stats_policy.rb
  app/policies/admin/user_policy.rb
  app/policies/admin/vaccination_center_policy.rb
  app/views/layouts/_admin_navbar.html.erb
  config/routes.rb
Labels: ready for review

#517 Remove checked_value and uncheck_value from input with as: :boolean
  app/views/admin/vaccination_centers/edit.html.erb
  app/views/admin/vaccination_centers/new.html.erb
  app/views/partners/vaccination_centers/new.html.erb
  app/views/users/_input_statement.html.erb
  app/views/users/_input_toc.html.erb
Labels: P1, bug, ready for review

#524 Ne pas stocker l'adresse
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_map.scss
  app/controllers/users_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/leaflet_map.js
  app/javascript/plugins/places_autocomplete.js
  app/javascript/plugins/user_map.js
  app/jobs/reverse_geocode_resource_job.rb
  app/models/user.rb
  app/services/randomize_coordinates_service.rb
  app/services/reverse_geocoding_service.rb
  app/views/users/_form.html.erb
  app/views/users/show.html.erb
  spec/factories/user_factory.rb
  spec/jobs/geocode_resource_job_spec.rb
  spec/models/user_spec.rb
  spec/system/user_spec.rb
Labels: P1

#530 Simplification des mentions légales
  app/views/partners/_mentions.html.erb
  app/views/partners/new.html.erb
  app/views/users/_form.html.erb
  app/views/users/_input_statement.html.erb
  app/views/users/_mentions.html.erb
  app/views/users/show.html.erb
Labels: P1, ready for review

#531 Ne pas demander nom/prénom au moment de l'inscription mais lors de la confirmation du match
  Gemfile
  app/controllers/matches_controller.rb
  app/controllers/users_controller.rb
  app/models/match.rb
  app/models/partner.rb
  app/models/user.rb
  app/models/vaccination_center.rb
  app/views/admin/home/index.html.erb
  app/views/admin/vaccination_centers/index.html.erb
  app/views/admin/vaccination_centers/show.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/layouts/_admin_navbar.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/match_mailer/match_confirmation_instructions.html.erb
  app/views/match_mailer/send_anonymisation_notice.html.erb
  app/views/matches/_confirmed.html.erb
  app/views/matches/_match_details.html.erb
  app/views/matches/_pending.html.erb
  app/views/partners/campaigns/show.html.erb
  app/views/users/_form.html.erb
  app/views/users/show.html.erb
  lib/tasks/populate.rake
  spec/factories/match_factory.rb
  spec/models/partner_spec.rb
  spec/models/user_spec.rb
  spec/requests/matches_request_spec.rb
  spec/system/matches_controller_spec.rb
  spec/system/user_spec.rb
  test/mailers/previews/match_mailer_preview.rb
Labels: P1, ready for review

#520 [Algolia] Scoping sur FR + DOM/TOM, rajout de la region dans l'adresse
  app/javascript/plugins/places_autocomplete.js
Labels: P2, ready for review

#538 Redis lock pour empêcher les match doublons
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  app/jobs/send_campaign_job.rb
  app/models/match.rb
  config/initializers/redlock.rb
Labels: ready for review

#544 Tweak mentions legal suivant recos MWE
  app/views/partners/_mentions.html.erb
  app/views/users/_mentions.html.erb
Labels: P1, ready for review

#539 Track clicks sur les matches
  app/controllers/matches_controller.rb
  app/jobs/send_match_sms_job.rb
  app/views/match_mailer/match_confirmation_instructions.html.erb
  config/routes.rb
  db/migrate/20210423073642_add_clicked_at_to_matches.rb
  db/schema.rb
  lib/tasks/batches.rake
  spec/requests/matches_request_spec.rb
  spec/spec_helper.rb
  spec/system/matches_controller_spec.rb
Labels: ready for review

#542 Passwordless
  Gemfile
  Gemfile.lock
  app/controllers/confirmations_controller.rb
  app/controllers/devise/passwordless/magic_links_controller.rb
  app/controllers/devise/passwordless/sessions_controller.rb
  app/models/user.rb
  app/views/devise/mailer/magic_link.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/users/_form.html.erb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/locales/devise.fr.yml
  config/routes.rb
  db/frozen_records/faq_items.yml
  spec/factories/user_factory.rb
  spec/models/user_spec.rb
  spec/system/user_spec.rb
Labels: P1, ready for review

#558 Rajouter le lien magique en plain text également en dessous du lien hypertexte
  app/views/devise/mailer/magic_link.html.erb
Labels: P1, ready for review

#557 Fix validation bug by asking for user to approve the CGU/TOS
  app/controllers/matches_controller.rb
  app/controllers/partners_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/matches/_pending.html.erb
  db/migrate/20210424105052_add_confirmation_failed_at_to_matches.rb
  db/schema.rb
  spec/requests/matches_request_spec.rb
  spec/system/matches_controller_spec.rb
Labels: P1, ready for review

#583 Ajout de cabinet infirmier au Vaccination Center Kind
  app/models/vaccination_center.rb
  app/views/partners/vaccination_centers/new.html.erb
Labels: ready for review

#586 Modifier email + sms de matching
  app/jobs/send_match_sms_job.rb
  app/mailers/match_mailer.rb
  app/views/match_mailer/match_confirmation_instructions.html.erb
Labels: P1

#598 [Match] Afficher l'adresse du centre uniquement quand confirmé ou lat/lon manquant
  app/helpers/application_helper.rb
  app/views/matches/_match_details.html.erb
  spec/helpers/application_helper_spec.rb
  spec/system/matches_controller_spec.rb
Labels: P1

#612 [Match] Stocker la distance entre le volontaire et le centre de vaccination à la création
  app/models/match.rb
  db/migrate/20210427112116_add_distance_to_matches.rb
  db/schema.rb
  spec/factories/vaccination_center_factory.rb
  spec/models/match_spec.rb
Labels: P1

#641 [Homepage V2] Intégration de la maquette figma + bandeau donateurs
  app/assets/images/home/comment-ca-marche.svg
  app/assets/images/home/icon-check-circle.svg
  app/assets/images/home/pourquoi-ce-projet.svg
  app/assets/images/home/time-value.svg
  app/assets/images/home/twitter-covidlist-creation.svg
  app/assets/stylesheets/components/_background.scss
  app/assets/stylesheets/components/fields/_checkbox.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_navbar.scss
  app/controllers/users_controller.rb
  app/javascript/components/confirmation.js
  app/javascript/components/smooth_scroll_anchor.js
  app/javascript/packs/application.js
  app/models/user.rb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_banner.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/admin_application.html.erb
  app/views/layouts/application.html.erb
  app/views/users/_about.html.erb
  app/views/users/_form.html.erb
  app/views/users/_input_statement.html.erb
  app/views/users/_input_toc.html.erb
  app/views/users/_mentions.html.erb
  app/views/users/new.html.erb
  app/views/users/shared/_box_cta.html.erb
  app/views/users/shared/_registration_success.html.erb
  spec/system/home_spec.rb
  spec/system/user_spec.rb
Labels: P1, ready for review

#661 Ordre d'affichage des rangs donateurs + UX de la page
  app/views/pages/_donateurs_list.html.erb
  app/views/pages/_donateurs_reward.html.erb
  app/views/pages/donateurs.html.erb
Labels: ready for review

#662 Afficher Ville, Code postal et Région avant confirmation d'un match
  app/models/vaccination_center.rb
  app/views/matches/_match_details.html.erb
  app/views/matches/show.html.erb
  db/migrate/20210429122735_add_city_zipcode_to_vaccination_centers.rb
  db/schema.rb
Labels: P1

#676 Typo vaccination center page and home page
  app/views/partners/vaccination_centers/new.html.erb
  app/views/users/new.html.erb
Labels: ready for review

#680 Add ulule_buddy_orders json to replace big amount by deposit bank
  app/assets/images/ulule_buddy_orders/order-5353839.jpeg
  app/controllers/pages_controller.rb
  app/models/ulule_buddy_order.rb
  app/services/ulule_service.rb
  app/views/pages/_donateurs_list.html.erb
  app/views/pages/_donateurs_reward.html.erb
  app/views/pages/donateurs.html.erb
  app/views/pages/donateurs/_orders.html.erb
  db/frozen_records/ulule_buddy_orders.json
Labels: P1

#650 Added some doc to help newcomers to help with reviews
  doc/contributing.md
Labels: P3, Tech, documentation

#685 Add lockable to partners
  app/models/partner.rb
  app/views/devise/mailer/unlock_instructions.html.erb
  config/initializers/devise.rb
  db/migrate/20210430072418_add_lockable_to_partners.rb
  db/schema.rb
Labels: P1, ready for review

#683 Lien de suppression d'un compte depuis l'email de match
  app/controllers/matches/users_controller.rb
  app/controllers/matches_controller.rb
  app/policies/match_policy.rb
  app/views/match_mailer/match_confirmation_instructions.html.erb
  app/views/matches/users/edit.html.erb
  config/routes.rb
  spec/system/matches/destroy_user_account_spec.rb
Labels: P1

#691 Matches/fix errors when user nil
  app/controllers/matches_controller.rb
  app/models/user.rb
  spec/system/matches_controller_spec.rb
Labels: appsignal
